export const GET_TOP_SALES = 'GET_TOP_SALES';
export const GET_TOP_SALES_SUCCESS = 'GET_TOP_SALES_SUCCESS';
export const GET_TOP_SALES_FAILED = 'GET_TOP_SALES_FAILED';

export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAILED = 'GET_CATEGORIES_FAILED';

export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILED = 'GET_PRODUCTS_FAILED';
export const CHANGE_PRODUCTS_OFFSET = 'CHANGE_PRODUCTS_OFFSET';
export const CHANGE_PRODUCTS_CATEGORY = 'CHANGE_PRODUCT_CATEGORY';
export const GET_PRODUCTS_FULL = 'GET_PRODUCTS_FULL';

export const CHANGE_QUERY = 'CHANGE_QUERY';

export const ADD_ITEM_IN_CART = 'ADD_ITEM_IN_CART';
export const DELETE_ITEM_FROM_CART = 'DELETE_ITEM_FROM_CART';
export const LOAD_CART_DATA = 'LOAD_CART_DATA';
